# Generated by Django 4.2.6 on 2024-01-20 20:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_stock', '0004_tipooperacion_conversionmedida'),
        ('base', '0003_sucursal_deposito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0003_alter_caja_empresa_alter_concepto_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('numero', models.IntegerField()),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('observacion', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deposito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.deposito')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.empresa')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
                ('tipo_operacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='control_stock.tipooperacion')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'movimientos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('cantidad', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cabmovimiento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control_stock.producto')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control_stock.unidadmedida')),
            ],
            options={
                'verbose_name': 'Detalle de Movimiento',
                'verbose_name_plural': 'Detalles de Movimiento',
                'db_table': 'movimientos_det',
                'ordering': ['movimiento'],
            },
        ),
    ]
