# Generated by Django 4.2.6 on 2024-01-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_cabmovimiento_detmovimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='detmovimiento',
            name='costo_docu',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='detmovimiento',
            name='costo_mmnn',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
