# Generated by Django 4.2.6 on 2024-01-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_stock', '0002_alter_categoria_empresa_alter_producto_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Cód. Barra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_fabrica',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Cód. Fábrica'),
        ),
    ]
