# Generated by Django 4.2.6 on 2024-01-20 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_sucursal_deposito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control_stock', '0003_alter_producto_codigo_barra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('descripcion', models.CharField(max_length=100, unique=True, verbose_name='Descripción')),
                ('sigla', models.CharField(max_length=20, unique=True, verbose_name='Sigla')),
                ('tipo', models.CharField(blank=True, choices=[('S', 'Suma'), ('R', 'Resta')], max_length=2, null=True)),
                ('afecta_costo', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.empresa', verbose_name='Empresa')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo Operacion',
                'verbose_name_plural': 'Tipos operaciones',
                'db_table': 'tipos_operaciones_stock',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConversionMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('operacion', models.CharField(choices=[('Multiplica', 'MULTIPLICA'), ('Divide', 'DIVIDE'), ('Potencia', 'POTENCIA')], max_length=20)),
                ('valor', models.FloatField(default=0.0)),
                ('activo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('medida_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medida_a', to='control_stock.unidadmedida')),
                ('medida_de', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medida_de', to='control_stock.unidadmedida')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversion de medida',
                'verbose_name_plural': 'Conversiones de Medidas',
                'db_table': 'conversiones_medidas',
                'ordering': ['id'],
            },
        ),
    ]
