# Generated by Django 4.2.6 on 2024-02-04 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_sucursal_deposito'),
        ('control_stock', '0005_alter_conversionmedida_operacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ['id'], 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.CreateModel(
            name='MovimientoProductoFecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('saldo_anterior', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('entrada', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('salida', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.deposito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control_stock.producto')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control_stock.unidadmedida')),
            ],
            options={
                'verbose_name': 'Movimiento de producto por fecha',
                'verbose_name_plural': 'Movimientos de productos por fecha',
                'db_table': 'movimientos_productos_fecha',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExistenciaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.deposito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control_stock.producto')),
            ],
            options={
                'verbose_name': 'Existencia de producto',
                'verbose_name_plural': 'Existencias de productos',
                'db_table': 'existencias_productos',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='movimientoproductofecha',
            constraint=models.UniqueConstraint(fields=('deposito', 'producto'), name='movimientos_productos_fecha_pk'),
        ),
        migrations.AddConstraint(
            model_name='existenciaproducto',
            constraint=models.UniqueConstraint(fields=('deposito', 'producto'), name='existencia_producto_pk'),
        ),
    ]
