# Generated by Django 4.2.6 on 2024-01-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('descripcion', models.CharField(max_length=80)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('descripcion', models.CharField(max_length=80)),
                ('sigla', models.CharField(max_length=5, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Países',
                'db_table': 'paises',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_fantasia', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_persona', models.CharField(blank=True, choices=[('F', 'Físico'), ('J', 'Jurídico')], max_length=1, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('S', 'Soltero/a'), ('C', 'Casado/a'), ('V', 'Viudo/a'), ('D', 'Divorciado/a')], max_length=2, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'db_table': 'personas',
                'ordering': ['id'],
            },
        ),
    ]
